### ISSUE TITLE
Feature Request: Per Page Page Setting

### ISSUE THREAD

**Issue by Azurewren** [agctute/relative-timestamps#1]
Currently the timestamp is for the whole vault. Is it possible to have it apply to individual pages? 

The reset (or set) time could be different per page so different starting times can be used on different pages.

**Comment by agctute** [comment]
Thanks for posting. I think I see what you mean. Right now I'm working on incorporating the ability to save a selected time instead of resetting it, after that, maybe a feature/command to automatically set the page time?

**Comment by agctute** [comment]
Added feature to plugin, should be good now
