### ISSUE TITLE
Feature Request: Settings

### ISSUE THREAD

**Issue by Azurewren** [agctute/relative-timestamps#2]
It would be great to have the ability to customise the moment.js time format used. That way people can use something other than `hh:mm A` without modifying the `main.js` file :)

**Comment by agctute** [comment]
Thanks for the feedback! I'll work on it but you're welcome to submit a PR for this if you have any good ideas.

**Comment by agctute** [comment]
Added in 1.0.2. Make an issue or PR if there's anything else that should be added
